fail_fast: false
minimum_pre_commit_version: "2.6.0"

repos:
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: "templates/.*"
      - id: mixed-line-ending

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 1d54ea2b9950097568c6a7a2e2bcb6d4b4ebfb61
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: examples/.*
      - id: terraform_docs
        args:
          - "--args=--config=.terraform-docs.yaml"
          - "--args=--lockfile=false"
      - id: terraform_providers_lock
      - id: terraform_tflint
        exclude: 'examples/.*'
        args:
          - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"
      - id: terraform_tfsec
        args:
          - "--args=--exclude-downloaded-modules"
          - "--args=--custom-check-dir=__GIT_WORKING_DIR__/.tfsec"
        files: \.tf$
        exclude: \.terraform\/.*$