repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: "templates/.*"
      - id: mixed-line-ending

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.3
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
        exclude: examples/.*
      - id: terraform_docs
        args:
          - "--args=--lockfile=false"
#      - id: terraform_providers_lock
#      - id: terraform_tflint
#        exclude: 'examples/.*'
      - id: terraform_tfsec
        args:
          - "--args=--exclude-downloaded-modules"
          - "--args=--custom-check-dir=__GIT_WORKING_DIR__/.tfsec"
        files: \.tf$
        exclude: \.terraform\/.*$